config/routes.rb
Rails.application.routes.draw do
  get "stories",  to: "pages#stories"
  resources :charges
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  def new
  end

  def create
    @amount = params[:amount]
    @token = params[:stripeToken]

    @amount = @amount.gsub('$', '').gsub(',', '')

    

    begin
      @amount = Float(@amount).round(2)
    rescue
      flash[:error] = 'Charge not completed. Please enter a valid amount in USD ($).'
      redirect_to new_charge_path
      return
    end

  @amount = (@amount * 100).to_i # Must be an integer!

  if @amount < 100
    flash[:error] = 'Charge not completed. Donation amount must be at least $1.'
    redirect_to new_charge_path
    return
  end

  Stripe::Charge.create(
    :amount => @amount,
    :currency => 'usd',
    :source => @token,
    :description => 'Custom donation'
    )



rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def stories
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/charges/create.html.erb
<h2>Thank you!</h2>
<p>Your donation of <strong><%= number_to_currency(@amount * 0.01) %></strong>
 has been received.</p>

app/views/charges/new.html.erb
 <div class="row">
   <div class="col m2"></div>
   <div class="col  m10">
     <div class="card  purple darken-4 form-container
     ">
     <div class="row">
       <div class="col m3"></div>
       <div class="col m3">

         <div class="card   green darken-4">
          <div class="card-content white-text">

            <h4>Instructions:</h4>
            <ol>
              <li>Amount must be in US Dollars.</li>
              <li>Amount must be more than or equal to a dollar.</li>
              <br><br>

            </ol>
          </div>
        </div>

      </div>
      <div class="col s12 m3">
        <div class="card green darken-4">
          <div class="card-content white-text">


            <%= form_tag charges_path do %>
            <div id="error_explanation">
              <% if flash[:error].present? %>
              <p><%= flash[:error] %></p>
              <% end %>
            </div>
            <article>
              <span class="donation"><%= label_tag(:amount, 'Donation Amount:') %></span>
              <%= text_field_tag(:amount) %>
            </article>
            <article>
              <%= hidden_field_tag(:stripeToken) %>
            </article>
            <button id='donateButton' class="btn">Donate</button>
            <% end %>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<script src="https://checkout.stripe.com/checkout.js"></script>

<script>
  var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    locale: 'auto',
    name: 'Donation For Ron',
    description: 'One-time donation',
    token: function(token) {
      $('input#stripeToken').val(token.id);
      $('form').submit();
    }
  });
  $('#donateButton').on('click', function(e) {
    e.preventDefault();

    $('#error_explanation').html('');

    var amount = $('input#amount').val();
    amount = amount.replace(/\$/g, '').replace(/\,/g, '')

    amount = parseFloat(amount);

    if (isNaN(amount)) {
      $('#error_explanation').html('<p>Please enter a valid amount in USD ($).</p>');
    }
    else if (amount < 1.00) {
      $('#error_explanation').html('<p>Donation amount must be at least $1.</p>');
    }
    else {
    amount = amount * 100; // Needs to be an integer!
    handler.open({
      amount: Math.round(amount)
    })
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpRon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/nav" %>

    <% if current_page?("/") %>
      
    
    <section>
    <%= yield %>
    </section>

    <% else %>
    <section class="sectioner">
    <%= yield %>
    </section>
    <% end %>
    <footer>
      <p> © JJ Keeney | 2017 All transactions are passed through Stripe, a secure way to transfer money on the internet. Learn more at <a href="https://stripe.com/" target="_blank">Stripe.com</a></p>
    </footer>
  </body>
</html>



      
    

app/views/pages/home.html.erb
<h1>Welcome to Help Ron</h1>
<%= link_to "Donate", new_charge_path, class: "btn" %>
<%= link_to "Learn More", stories_path, class: "btn" %>

app/views/shared/_nav.html.erb
<div class="fixed-action-btn horizontal click-to-toggle">
    <a class="btn-floating btn-large red">
      <i class="material-icons">menu</i>
    </a>
    <ul>
      <li><a class="btn-floating blue", href="/stories"><i class="material-icons">help</i></a></li>
      <li><a class="btn-floating green darken-1", href="/charges/new"><i class="material-icons">attach_money</i></a></li>
      <li><a class="btn-floating yellow", href="/"><i class="material-icons">home</i></a></li>

    </ul>
  </div>